<script lang="ts">
  import { get } from "svelte/store";
  import Plus from "../../assets/feather/Plus.svelte";
  import {
    contextMenuStore,
    currentRoute,
    settingsJson,
  } from "../../stores/stateStore";
  import Alert from "../settings/Alert.svelte";
  import icon from "../../assets/icon/nest.png";

  let savePath = $settingsJson.savePath;
  let prevSavePath = "";
  let wasSavePathChanged = false;

  let combineBehavior = $settingsJson.combineBehavior;

  async function closeModal() {
    $settingsJson.combineBehavior = combineBehavior;
    await window.electron.updateSettingsJson(get(settingsJson));
    $contextMenuStore.openModal = "";
  }
</script>

<div>
  <div class="flex items-center justify-center">
    <img class="w-16 h-16" src={icon} alt="" />
    <h1 class="ml-4 font-mono text-3xl font-extrabold text-center">TagNest</h1>
  </div>
  <h2 class="text-xl font-bold">Welcome!</h2>
  <div class="text-sm">
    TagNest is a tool to organize your bookmarks and files using tags. You can
    save bookmarks using the <a
      target="_blank"
      class="underline text-primary"
      href="https://github.com/dadonc/eTags/tree/main/chrome_extension"
      >Chrome extension</a
    >, or click on the
    <!-- <span title="Add item" class="inline-block w-4 h-4 align-middle">
      <Plus />
    </span> -->
    <div
      title="Add item"
      class="h-8 mx-1 text-sm font-normal capitalize rounded hover:bg-base-100 hover:text-base-content hover:border-base-content hover:cursor-default btn btn-outline btn-sm text-base-content"
    >
      Import
      <span class="inline-block w-4 h-4 ml-2">
        <Plus />
      </span>
    </div>
    button in the top right corner to start importing files.
  </div>
  <h2 class="mt-4 text-xl font-bold">Inital settings</h2>
  <!-- <div class="text-sm">
    You can also change these settings later in the settings menu.
  </div> -->

  <div class="mt-2">
    <div class="font-bold">Database folder</div>
    <div class="text-sm">
      Choose the save folder for the database and the autogenerated preview
      files. This can be changed to allow syncing with cloud storage services.
    </div>
    <div class="flex justify-center mt-4">
      <button
        class="p-2 text-xs italic break-all rounded-md bg-base-300 text-primary"
        on:click={async () => {
          const newPath = await window.electron.getNewSavePath();
          if (newPath && newPath !== savePath) {
            prevSavePath = savePath;
            savePath = newPath;
            wasSavePathChanged = true;
          }
        }}>{savePath}</button
      >
    </div>
    {#if wasSavePathChanged}
      <div class="p-4">
        <Alert
          classNames=""
          header="Pending changes"
          body="Please restart the application for changes to take effect."
          buttonText="Restart"
          buttonAutoFocus={true}
          buttonAction={async () => {
            $settingsJson.savePath = savePath;
            await window.electron.updateSettingsJson(get(settingsJson));
            window.electron.restartApp();
          }}
        />
      </div>
    {/if}
  </div>
  <div>
    <div class="font-bold">Import</div>
    <div class="text-sm">
      How should imported files be treated? They can either be copied to the
      database folder, moved to the database folder or left in their original
      location.
    </div>
    <select
      class="mt-2"
      on:change={(e) => {
        // @ts-ignore
        if (e.target.value !== $settingsJson.combineBehavior) {
          // @ts-ignore
          combineBehavior = e.target.value;
        }
      }}
    >
      <option selected={combineBehavior === "copy"} value="copy">Copy</option>
      <option selected={combineBehavior === "move"} value="move">Move</option>
      <option selected={combineBehavior === "separate"} value="separate"
        >Keep original path</option
      >
    </select>
  </div>

  <h2 class="mt-4 text-xl font-bold">Some tips</h2>
  <ul class="text-sm list-disc">
    <li>Right-click on an item in the grid for additional actions</li>
    <li>Right-click on a tag in the tags list for additional actions</li>
    <li>Right-click on a video seek bar to highlight this position</li>
    <li>Select text in bookmarks to create highlights</li>
    <li>
      Most of macOS's default keyboard shortcut work as expected, some less
      obvious ones can be found on the <button
        class="text-primary"
        on:click={() => {
          $currentRoute = "settings";
        }}>settings</button
      > page
    </li>
  </ul>

  <div class="flex items-center justify-center mt-8 mb-4">
    <button class="btn btn-primary" on:click={closeModal}>Let's go</button>
  </div>
</div>

<style>
  li {
    margin-left: 1.5rem;
  }
</style>
