<script lang="ts">
  import Plus from "../../assets/feather/Plus.svelte";
  import { contextMenuStore } from "../../stores/stateStore";

  function closeModal() {
    $contextMenuStore.openModal = "";
  }
</script>

<div>
  <h1>TagNest</h1>
  <h2 class="text-xl font-bold">Welcome!</h2>
  <div>
    TagNest is a tool to organize your bookmarks and files with tags. You can
    save bookmarks offline using the <a
      target="_blank"
      class="text-blue-500"
      href="https://github.com/dadonc/eTags/tree/main/chrome_extension"
      >Chrome extension</a
    >, or click on the
    <span title="Add item" class="inline-block w-4 h-4 align-middle">
      <Plus />
    </span>
    icon in the top right corner to start importing files.
  </div>
  <h2 class="mt-4 text-xl font-bold">Inital settings</h2>
  <div class="text-xs">
    You can change these settings later in the settings menu.
  </div>

  <div class="my-2">
    Choose the save folder for the database and the autogenerated preview files.
  </div>
  <div>
    How should imported files be treated? They can either be copied to the
    database folder, moved to the database folder or left in their original
    location.
  </div>

  <h2 class="mt-4 text-xl font-bold">Some tips</h2>
  <ul>
    <li>
      Right-click on either an item in the grid or a tag in the tag list for
      additional actions
    </li>
    <li>Select text in bookmarks to create highlights</li>
    <li>Right-click on a video seek bar to highlight this timestamp</li>
    <li>
      Most of macOS's default keyboard shortcut work as expected, some less
      obvious ones can be found on the settings page
    </li>
  </ul>

  <div class="flex items-center justify-center mt-8">
    <button class="btn btn-primary" on:click={closeModal}>Let's go</button>
  </div>
</div>
